version: '2'
services:
  php:
    build: docker/php
    links:
      - elasticsearch
    volumes:
      - .:/var/www/html
      - ./log:/var/log
  elasticsearch:
    image: elasticsearch:2.3.5
    ports:
      - 9200:9200
    #volumes:
    #  - ./data/elasticsearch/:/usr/share/elasticsearch/data
